# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
stages:
  - stage: Build
    jobs:
      - job: BuildWebApp
        pool:
          vmImage: ubuntu-latest
        steps:
         - task: ArchiveFiles@2
           inputs:
             rootFolderOrFile: '$(Build.BinariesDirectory)'
             includeRootFolder: false
         - task: PublishBuildArtifacts@1