trigger:
- 'master'

variables:
  buildConfiguration: 'Release'
  releaseBranchName: 'release'

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
       - task: ArchiveFiles@2
         displayName: "Arhieve files"
         inputs:
           rootFolderOrFile: '$(build.sourcesDirectory)'
           includeRootFolder: false
       - task: PublishBuildArtifacts@1
         displayName: "Publish artifacts"