# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: BuildWebApp
        steps:
         - task: ArchiveFiles@2
           inputs:
             rootFolderOrFile: '$(Build.BinariesDirectory)'
             includeRootFolder: false
         - task: PublishBuildArtifacts@1
  - stage: Prod
    jobs:
      - job: deployProd
        steps:
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.DefaultWorkingDirectory)'
        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'azure subscription for lab #1 (85145e52-ffb3-41f3-a9fe-73100ed964a0)'
            appType: 'webApp'
            WebAppName: 'bookstore2'
            packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
