trigger:
- 'master'

variables:
  buildConfiguration: 'Release'
  releaseBranchName: 'release'

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
       - task: ArchiveFiles@2
         displayName: "Arhieve files"
         inputs:
           rootFolderOrFile: '$(build.sourcesDirectory)'
           includeRootFolder: false
       - task: PublishBuildArtifacts@1
         displayName: "Publish artifacts"
       - task: DownloadBuildArtifacts@1
         displayName: "Download artifacts"
         inputs:
           buildType: 'current'
           downloadType: 'specific'
           downloadPath: '$(System.ArtifactsDirectory)'
           cleanDestinationFolder: true
       - task: AzureRmWebAppDeployment@4
         displayName: "push code to azure web app"
         inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'azure subscription for lab #1 (85145e52-ffb3-41f3-a9fe-73100ed964a0)'
            appType: 'webApp'
            WebAppName: 'bookstore2'
            packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'